import { createClient } from '@supabase/supabase-js';
import { LeaderboardEntry } from '../types';

const supabaseUrl = 'https://occqvxiaxafrplyszzdy.supabase.co';
const supabaseKey = 'sb_publishable_UWC1srUuuwrw4c8k7U9LPA_I--GEjTD';

export const supabase = createClient(supabaseUrl, supabaseKey);

const LOCAL_STORAGE_KEY = 'starfighter_leaderboard';

const getLocalScores = (): LeaderboardEntry[] => {
  try {
    const stored = localStorage.getItem(LOCAL_STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
};

const saveLocalScore = (entry: LeaderboardEntry) => {
  const scores = getLocalScores();
  scores.push(entry);
  scores.sort((a, b) => b.score - a.score);
  // Keep top 10 locally
  localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(scores.slice(0, 10)));
};

export const fetchLeaderboard = async (): Promise<LeaderboardEntry[]> => {
  try {
    const { data, error } = await supabase
      .from('leaderboard')
      .select('*')
      .order('score', { ascending: false })
      .limit(10);

    if (error) {
      // If table is missing (42P01) or other error, fallback to local storage
      console.warn('Supabase Leaderboard unavailable (using local backup):', error.message);
      if (error.code === '42P01') {
        console.info('%c IMPORTANT: Run this SQL in your Supabase SQL Editor to create the table: \n\n create table leaderboard ( id bigint generated by default as identity primary key, username text not null, score int not null, level int not null, created_at timestamp with time zone default timezone(\'utc\'::text, now()) not null );', 'color: #00ffff; font-weight: bold;');
      }
      return getLocalScores();
    }
    
    return data as LeaderboardEntry[];
  } catch (err) {
    console.warn('Network error, defaulting to local scores:', err);
    return getLocalScores();
  }
};

export const submitScore = async (username: string, score: number, level: number) => {
  const newEntry: LeaderboardEntry = {
    id: Date.now(), // Temporary ID for local use
    username,
    score,
    level,
    created_at: new Date().toISOString()
  };

  // Always save locally first ensures the user sees their score immediately
  saveLocalScore(newEntry);

  try {
    const { error } = await supabase
      .from('leaderboard')
      .insert([
        { username, score, level }
      ]);

    if (error) {
      console.warn('Failed to sync score to cloud:', error.message);
      return true; // Return true because we saved it locally
    }
    return true;
  } catch (err) {
    console.warn('Supabase submission error:', err);
    return true; // Return true because we saved it locally
  }
};